# -*- coding: utf-8 -*-
"""pp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HleI_WLHhyQGGvLVFGU0XjqhmdTYHWq
"""

!pip install transformers datasets torch torchaudio soundfile librosa scikit-learn

# Option A — upload a zip of your data folder
from google.colab import files
uploaded = files.upload()  # upload data.zip

!unzip data.zip -d /content/data

import os
print(os.listdir('/content/src'))

import sys
sys.path.insert(0, '/content/src')  # point to src/ instead of /content

from dataset import build_dataloaders

import sys
sys.path.insert(0, '/content')

from dataset import build_dataloaders
from model import AudioDeepfakeDetector
from trainer import Trainer
import torch

print("GPU available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

# Config
REAL_DIR      = "/content/data/data/real"
SYNTHETIC_DIR = "/content/data/data/synth"
BATCH_SIZE    = 16
PHASE1_EPOCHS = 10
PHASE2_EPOCHS = 10

# Build data
train_loader, val_loader, test_loader = build_dataloaders(
    real_dir=REAL_DIR,
    synthetic_dir=SYNTHETIC_DIR,
    batch_size=BATCH_SIZE,
)

# Build model
model = AudioDeepfakeDetector(
    encoder_name="wav2vec2-base",
    freeze_encoder=True,
)

# Train
trainer = Trainer(model, train_loader, val_loader, checkpoint_dir="/content/models")
trainer.train(
    phase1_epochs=PHASE1_EPOCHS,
    phase2_epochs=PHASE2_EPOCHS,
)